
package VIEW;
import MODEL.Model_fees;
import DAO.D_fees;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Form_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Form_GUI
     */
    public Form_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        student_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        reg_number_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        depart_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        academic_field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        programme_field = new javax.swing.JTextField();
        trimester_field = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        supervision_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        reg_field = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        grad_field = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        display_field = new javax.swing.JTextField();
        annual_btn = new javax.swing.JButton();
        three_btn = new javax.swing.JButton();
        reg_btn = new javax.swing.JButton();
        retrieve_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        clear_btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Home");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Fianance");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Students");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("UTB MIS");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("Programmes");

        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setText("ONLINE UTB STUDENTS FEES MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Student-Names:");

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Studen Names", "Trimester Fees", "Supervision Fees", "Graduation Fees"
            }
        ));
        jScrollPane1.setViewportView(data_table);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Registration-Number:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Department:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Academic-Year:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Programme:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Trimester-Fees:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Supervision-Fees:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Registration Fees/Year");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Graduation-Fees");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel19.setText("DISPLAY FEES HERE:");

        annual_btn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        annual_btn.setText("ANNUAL FEES");
        annual_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annual_btnActionPerformed(evt);
            }
        });

        three_btn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        three_btn.setText("3 YEARS FEES");
        three_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_btnActionPerformed(evt);
            }
        });

        reg_btn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        reg_btn.setText("REGISTER FEES");
        reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnActionPerformed(evt);
            }
        });

        retrieve_btn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        retrieve_btn.setText("RETRIEVE FEES");
        retrieve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieve_btnActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clear_btn.setText("DELETE");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        clear_btn2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clear_btn2.setText("Clear");
        clear_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton5)
                        .addGap(57, 57, 57)
                        .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)
                                        .addComponent(student_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(35, 35, 35)
                                        .addComponent(reg_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(35, 35, 35)
                                        .addComponent(depart_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(35, 35, 35)
                                        .addComponent(academic_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(35, 35, 35)
                                        .addComponent(programme_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(35, 35, 35)
                                        .addComponent(trimester_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(35, 35, 35)
                                        .addComponent(supervision_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(35, 35, 35)
                                        .addComponent(reg_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(35, 35, 35)
                                        .addComponent(grad_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(annual_btn)
                                .addGap(68, 68, 68)
                                .addComponent(three_btn)
                                .addGap(73, 73, 73)
                                .addComponent(reg_btn)
                                .addGap(85, 85, 85)
                                .addComponent(retrieve_btn)
                                .addGap(84, 84, 84)
                                .addComponent(clear_btn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel19)
                        .addGap(35, 35, 35)
                        .addComponent(display_field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(clear_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(student_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(reg_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(depart_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(academic_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(programme_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(trimester_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(supervision_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(reg_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(grad_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(display_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annual_btn)
                    .addComponent(three_btn)
                    .addComponent(reg_btn)
                    .addComponent(retrieve_btn)
                    .addComponent(clear_btn))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnActionPerformed
            Model_fees fee = new Model_fees();
            D_fees d_fee = new D_fees();

            // Retrieve values from text fields
            String student_names = student_field.getText();
            String reg_number = reg_number_field.getText();
            String department = depart_field.getText();
            String academic_year_str = academic_field.getText();
            String programme = programme_field.getText();
            String trim_fee_str = trimester_field.getText();
            String sup_fee_str = supervision_field.getText();
            String reg_fee_str = reg_field.getText();
            String grad_fee_str = grad_field.getText();

            // Validation
            if (student_names.isEmpty() || reg_number.isEmpty() || department.isEmpty() || academic_year_str.isEmpty() || programme.isEmpty() || trim_fee_str.isEmpty() || sup_fee_str.isEmpty() || reg_fee_str.isEmpty() || grad_fee_str.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all the requested fields");
                return; // halt the execution 
            }

            // Convert academic year, fees to numeric values
            int academic_year = Integer.parseInt(academic_year_str);
            double trim_fee = Double.parseDouble(trim_fee_str);
            double sup_fee = Double.parseDouble(sup_fee_str);
            double reg_fee = Double.parseDouble(reg_fee_str);
            double grad_fee = Double.parseDouble(grad_fee_str);

            // Additional validation for numeric values
            if (academic_year <= 0 || trim_fee <= 0 || sup_fee <= 0 || reg_fee <= 0 || grad_fee <= 0) {
                JOptionPane.showMessageDialog(null, "Invalid input for numeric fields");
                return; // halt the execution 
            }

            // Set fee information
            fee.setStudent_names(student_names);
            fee.setReg_number(reg_number);
            fee.setDepartment(department);
            fee.setAcademic_year(academic_year);
            fee.setProgramme(programme);
            fee.setTrimester_fees(trim_fee);
            fee.setSupervision_fees(sup_fee);
            fee.setRegistration_fees(reg_fee);
            fee.setGraduation_fees(grad_fee);

            // Insert fee information into the database
            d_fee.create_student(fee);

       
    }//GEN-LAST:event_reg_btnActionPerformed

    private void annual_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annual_btnActionPerformed
        String trim_fee_str = trimester_field.getText();
        String reg_fee_str = reg_field.getText();

        // Check if any of the required fields are empty
        if (trim_fee_str.isEmpty() || reg_fee_str.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields");
            return; // halt the execution 
        }

        // Perform calculation
        double trim_fee = Double.parseDouble(trim_fee_str);
        double reg_fee = Double.parseDouble(reg_fee_str);
        double total = (trim_fee + reg_fee ) * 3;

        display_field.setText(String.valueOf(total) +" Rwf");
        
    }//GEN-LAST:event_annual_btnActionPerformed

    private void three_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_btnActionPerformed
        String trim_fee_str = trimester_field.getText();
        String reg_fee_str = reg_field.getText();
        String sup_fee_str = supervision_field.getText();
        String grad_fee_str = grad_field.getText();

        // Check if any of the required fields are empty
        if (trim_fee_str.isEmpty() || reg_fee_str.isEmpty() || sup_fee_str.isEmpty() || grad_fee_str.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fields");
            return; // halt the execution 
        }

        // Perform calculation
        double trim_fee = Double.parseDouble(trim_fee_str);
        double reg_fee = Double.parseDouble(reg_fee_str);
        double sup_fee = Double.parseDouble(sup_fee_str);
        double grad_fee = Double.parseDouble(grad_fee_str);
        double total = (((trim_fee + reg_fee )*3)*3 )+ sup_fee + grad_fee;

        display_field.setText(String.valueOf(total)+" Rwf");
        
    }//GEN-LAST:event_three_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        
         // Clear input fields
         
         student_field.setText("");
         reg_number_field.setText("");
         depart_field.setText("");
         academic_field.setText("");
         programme_field.setText("");
         trimester_field.setText("");
         supervision_field.setText("");
         reg_field.setText("");
         grad_field.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
       this.dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void clear_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn2ActionPerformed
        display_field.setText("");
    }//GEN-LAST:event_clear_btn2ActionPerformed

    private void retrieve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieve_btnActionPerformed
      populateTable();
    }//GEN-LAST:event_retrieve_btnActionPerformed

    
    private void populateTable() {
        D_fees d_fee = new D_fees();
        DefaultTableModel model = (DefaultTableModel) data_table.getModel();

        model.setRowCount(0);

         List <Model_fees> fees = d_fee.display_students();

         for (Model_fees fee : fees){

             Object [] row = {

                 fee.getStudent_names(),
                 fee.getTrimester_fees(),
                 fee.getSupervision_fees(),
                 fee.getGraduation_fees()
             };

             model.addRow(row);
         }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academic_field;
    private javax.swing.JButton annual_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn2;
    private javax.swing.JTable data_table;
    private javax.swing.JTextField depart_field;
    private javax.swing.JTextField display_field;
    private javax.swing.JButton exit_btn;
    private javax.swing.JTextField grad_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField programme_field;
    private javax.swing.JButton reg_btn;
    private javax.swing.JTextField reg_field;
    private javax.swing.JTextField reg_number_field;
    private javax.swing.JButton retrieve_btn;
    private javax.swing.JTextField student_field;
    private javax.swing.JTextField supervision_field;
    private javax.swing.JButton three_btn;
    private javax.swing.JTextField trimester_field;
    // End of variables declaration//GEN-END:variables
}
